include: package:very_good_analysis/analysis_options.yaml
linter:
  rules:
    always_specify_types: false
    public_member_api_docs: false
    no_default_cases: false
    cascade_invocations: false
    lines_longer_than_80_chars: false
analyzer:
  errors:
    invalid_annotation_target: ignore
    inference_failure_on_function_invocation: ignore
