name: kanca
description: Kanca app
version: 1.0.0+1
publish_to: none

environment:
  sdk: ^3.8.0

dependencies:
  bloc: ^9.0.0
  envied: ^1.1.1
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_hooks: ^0.21.2
  flutter_localizations:
    sdk: flutter
  flutter_secure_storage: ^9.2.4
  flutter_svg: ^2.2.0
  freezed_annotation: ^3.1.0
  get_it: ^8.0.3
  google_fonts: ^6.2.1
  http: ^1.4.0
  intl: ^0.20.2
  json_annotation: ^4.9.0
  logger: ^2.6.0
  page_transition: ^2.2.1

dev_dependencies:
  bloc_test: ^10.0.0
  build_runner: ^2.5.4
  envied_generator: ^1.1.1
  flutter_gen_runner: ^5.10.0
  flutter_launcher_icons: ^0.14.4
  flutter_native_splash: ^2.4.6
  flutter_test:
    sdk: flutter
  freezed: ^3.1.0
  json_serializable: ^6.9.5
  mocktail: ^1.0.4
  very_good_analysis: ^9.0.0

flutter:
  assets:
    - assets/icons/
    - assets/images/
    - assets/mascots/
  generate: true
  uses-material-design: true

flutter_gen:
  output: lib/gen/
  line_length: 80
  integrations:
    flutter_svg: true

flutter_native_splash:
  color: "#FFF9ED"
  image: splash_screen.png
  color_dark: "#FFF9ED"
  image_dark: splash_screen.png

  android_12:
    color: "#FFF9ED"
    image: splash_screen.png
    color_dark: "#FFF9ED"
    image_dark: splash_screen.png

  android: true
  ios: true
  web: true
